[package]
name = "oregon-trail"
version = "0.1.0"
authors = ["Finn Wright <finnmcwright@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rand = "0.6.5"
redux-rs = "0.1"
